name = "uaw-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "https://uaw.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "uaw-db"
database_id = "978f5b98-1ce3-4fe8-ab47-cd6fbfacbb6d"
